### PR TITLE
fix access to ModalManager instance

### PR DESCRIPTION
**Pull request by atis--**
a way to fix https://github.com/jquense/react-bootstrap-modal/issues/28

### CODE REVIEW

**Comment by Pisi-Deff** [comment]
I'm glad someone has taken the time to work on this :)

Some thoughts:

What's the motivation behind removing the check for an existing `getZIndex` on line 95?

`getZIndex` is a module-wide variable and will be overwritten by each successive mounted Modal. The one declared by the Modal mounted last will then be used for all Modals.

If my assumption is correct that `this.manager`/`ref.props.manager` will refer to the same ModalManager instance for all Modals, then it might be better to:
* keep a module-wide variable reference to the ModalManager instance (on line 186 assign to this variable instead)
* keep the existing `getZIndex` check: `getZIndex = getZIndex || (function () {` so that the function is declared only once and not overwritten
* refer to the module-wide reference on line 113

**Comment by atis--** [comment]
I agree on all points. Please see the updated version.

**Comment by atis--** [comment]
Ok, even better. Please check if the new change looks alright to you.

**Comment by jquense** [comment]
thanks!

**Pull request merged**
